name: Playwright Docker Tests

on:
 push:
  branches:
   - '**'
 pull_request:
  branches:
   - '**'

jobs:
 test:
  runs-on: ubuntu-latest

  steps:

   - name: Log in to DockerHub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build Docker image
     run: docker build --target=base -t smalovitsa/e2eexeua:latest -f Dockerfile .

   - name: Push Docker image to DockerHub
     run: docker push smalovitsa/e2eexeua:latest

   - name: Docker pull
     run: docker pull smalovitsa/e2eexeua:latest

   - name: Run npm audit audit-check
     run: docker build --target=audit-check -f Dockerfile .

   - name: Run check sort-package-json
     run: docker build --target=check-package-json -f Dockerfile .

   - name: Run lint eslint
     run: docker build --target=lint-code -f Dockerfile .

   - name: Run Prettier format check
     run: docker build --target=format-check -f Dockerfile .
       
   - name: Run Cspell spell-check
     run: docker build --target=spell-check -f Dockerfile .

   - name: Build Docker image and artifacts
     run: docker build --build-arg DATE=$(date +%s) --target=export-report -t my-playwright-tests --output type=local,dest=./html-report -f Dockerfile .

   - name: Upload Playwright HTML Report
     uses: actions/upload-artifact@v4
     with:
      name: html-report
      path: html-report
