name: Playwright Docker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Логін в DockerHub (за потреби, якщо ваш образ на DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: smalovitsa
          password: ZXC6qwe$$

      # Крок 3: Встановлення Docker Buildx (для оптимізації білду)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Крок 4: Збірка Docker образу
      - name: Build Docker image
        run: docker build --build-arg DATE=$(date +%s) -t my-playwright-tests -f dockerfile.custom .

      # Крок 5: Запуск Docker контейнера для виконання тестів
      - name: Run Playwright tests in Docker
        run: docker run --rm -v $(pwd)/html-report:/app/html-report my-playwright-tests

      # Крок 6: Зберігаємо HTML звіт як артефакт GitHub Actions
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: html-report

