name: Playwright Docker Tests

on:
 push:
  branches:
   - '**'
 pull_request:
  branches:
   - '**'

jobs:
 postman-api-test:
  runs-on: ubuntu-latest

  steps:
  
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Install Node.js
     uses: actions/setup-node@v4
     with:
       node-version: '20.9.0'

   - name: Install Newman
     run: npm install -g newman

   - name: Run Postman Collection
     run: newman run ./postman/PrivatBankApi.json --reporters cli,html --reporter-html-report ./privatbank-api-test-report

   - name: Upload Newman HTML Report
     uses: actions/upload-artifact@v4
     with:
       name: privatbank-api-test-report
       path: privatbank-api-test-report


 test:
  runs-on: ubuntu-latest

  steps:

   - name: Log in to DockerHub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build Docker image
     run: docker build --target=base -t smalovitsa/e2eexeua:latest -f Dockerfile .

   - name: Push Docker image to DockerHub
     run: docker push smalovitsa/e2eexeua:latest

   - name: Cache Docker layers
     uses: docker/build-push-action@v6
     with:
       context: .
       file: ./Dockerfile
       tags: smalovitsa/e2eexeua:latest
       cache-from: type=gha
       cache-to: type=gha, mode=max
     
   - name: Docker pull
     run: docker pull smalovitsa/e2eexeua:latest

   - name: Build and test with bake
     run: docker buildx bake --file docker-bake.hcl
 
   - name: Upload Playwright HTML Report
     uses: actions/upload-artifact@v4
     with:
      name: html-report
      path: html-report

   - name: Upload NPM Audit HTML Report
     uses: actions/upload-artifact@v4
     with:
      name: npm-audit-report
      path: npm-audit-report

   - name: Upload eslint HTML Report
     uses: actions/upload-artifact@v4
     with:
      name: lint-report
      path: lint-report
