name: Playwright Docker Tests

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
#  format-check:
#   runs-on: ubuntu-latest

#   steps:
#    - name: Log in to DockerHub
#      uses: docker/login-action@v2
#      with:
#       username: smalovitsa
#       password: ZXC6qwe$$

#    - name: Checkout repository
#      uses: actions/checkout@v3

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3

#    - name: Docker pull
#      run: docker pull smalovitsa/e2eexeua:latest

#    - name: Run Prettier format check
#      run: docker build --target=format-check -f dockerfile.custom .

 test:
  runs-on: ubuntu-latest

  steps:
   - name: Log in to DockerHub
     uses: docker/login-action@v2
     with:
      username: smalovitsa
      password: ZXC6qwe$$

   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Docker pull
     run: docker pull smalovitsa/e2eexeua:latest

   - name: Run Prettier format check
     run: docker build --target=format-check -f dockerfile.custom .
  
   # Крок 1: Клонуємо репозиторій
   - name: Checkout repository
     uses: actions/checkout@v3

  #  # Крок 2: Логін в DockerHub (за потреби, якщо ваш образ на DockerHub)
  #  - name: Log in to DockerHub
  #    uses: docker/login-action@v2
  #    with:
  #     username: smalovitsa
  #     password: ZXC6qwe$$

   # Крок 3: Встановлення Docker Buildx (для оптимізації білду)
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Build Docker image
     run: docker build -t smalovitsa/e2eexeua:latest -f dockerfile .

   - name: Push Docker image to DockerHub
     run: docker push smalovitsa/e2eexeua:latest

   # Крок 4: Збірка Docker образу
   - name: Build Docker image and artifacts
     run: docker build --build-arg DATE=$(date +%s) --target=export-report -t my-playwright-tests --output type=local,dest=./html-report -f dockerfile.custom .

   # Крок 5: Зберігаємо HTML звіт як артефакт GitHub Actions
   - name: Upload Playwright HTML Report
     uses: actions/upload-artifact@v3
     with:
      name: html-report
      path: html-report
